require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe RescuecomptsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Rescuecompt. As you add validations to Rescuecompt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RescuecomptsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all rescuecompts as @rescuecompts" do
      rescuecompt = Rescuecompt.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:rescuecompts)).to eq([rescuecompt])
    end
  end

  describe "GET show" do
    it "assigns the requested rescuecompt as @rescuecompt" do
      rescuecompt = Rescuecompt.create! valid_attributes
      get :show, {:id => rescuecompt.to_param}, valid_session
      expect(assigns(:rescuecompt)).to eq(rescuecompt)
    end
  end

  describe "GET new" do
    it "assigns a new rescuecompt as @rescuecompt" do
      get :new, {}, valid_session
      expect(assigns(:rescuecompt)).to be_a_new(Rescuecompt)
    end
  end

  describe "GET edit" do
    it "assigns the requested rescuecompt as @rescuecompt" do
      rescuecompt = Rescuecompt.create! valid_attributes
      get :edit, {:id => rescuecompt.to_param}, valid_session
      expect(assigns(:rescuecompt)).to eq(rescuecompt)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Rescuecompt" do
        expect {
          post :create, {:rescuecompt => valid_attributes}, valid_session
        }.to change(Rescuecompt, :count).by(1)
      end

      it "assigns a newly created rescuecompt as @rescuecompt" do
        post :create, {:rescuecompt => valid_attributes}, valid_session
        expect(assigns(:rescuecompt)).to be_a(Rescuecompt)
        expect(assigns(:rescuecompt)).to be_persisted
      end

      it "redirects to the created rescuecompt" do
        post :create, {:rescuecompt => valid_attributes}, valid_session
        expect(response).to redirect_to(Rescuecompt.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved rescuecompt as @rescuecompt" do
        post :create, {:rescuecompt => invalid_attributes}, valid_session
        expect(assigns(:rescuecompt)).to be_a_new(Rescuecompt)
      end

      it "re-renders the 'new' template" do
        post :create, {:rescuecompt => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested rescuecompt" do
        rescuecompt = Rescuecompt.create! valid_attributes
        put :update, {:id => rescuecompt.to_param, :rescuecompt => new_attributes}, valid_session
        rescuecompt.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested rescuecompt as @rescuecompt" do
        rescuecompt = Rescuecompt.create! valid_attributes
        put :update, {:id => rescuecompt.to_param, :rescuecompt => valid_attributes}, valid_session
        expect(assigns(:rescuecompt)).to eq(rescuecompt)
      end

      it "redirects to the rescuecompt" do
        rescuecompt = Rescuecompt.create! valid_attributes
        put :update, {:id => rescuecompt.to_param, :rescuecompt => valid_attributes}, valid_session
        expect(response).to redirect_to(rescuecompt)
      end
    end

    describe "with invalid params" do
      it "assigns the rescuecompt as @rescuecompt" do
        rescuecompt = Rescuecompt.create! valid_attributes
        put :update, {:id => rescuecompt.to_param, :rescuecompt => invalid_attributes}, valid_session
        expect(assigns(:rescuecompt)).to eq(rescuecompt)
      end

      it "re-renders the 'edit' template" do
        rescuecompt = Rescuecompt.create! valid_attributes
        put :update, {:id => rescuecompt.to_param, :rescuecompt => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested rescuecompt" do
      rescuecompt = Rescuecompt.create! valid_attributes
      expect {
        delete :destroy, {:id => rescuecompt.to_param}, valid_session
      }.to change(Rescuecompt, :count).by(-1)
    end

    it "redirects to the rescuecompts list" do
      rescuecompt = Rescuecompt.create! valid_attributes
      delete :destroy, {:id => rescuecompt.to_param}, valid_session
      expect(response).to redirect_to(rescuecompts_url)
    end
  end

end
